version: '3'

services:
  app:
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/candidates_management_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_DB: candidates_management_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    hostname: db
    ports:
      - "5432:5432"

  flyway:
    image: redgate/flyway
    environment:
      FLYWAY_URL: jdbc:postgresql://db:5432/candidates_management_db
      FLYWAY_USER: postgres
      FLYWAY_PASSWORD: 1234
    volumes:
      - ./sql:/flyway/sql
    depends_on:
      - db
    command: -url=jdbc:postgresql://db:5432/candidates_management_db -schemas=public -user=postgres -password=1234 -connectRetries=60  migrate


