server:
  port: 8080

spring:
  servlet:
    multipart:
      max-request-size: 50MB
      max-file-size: 50MB
      file-size-threshold: 2KB
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
springdoc:
  swagger-ui:
    path: /doc/swagger-ui.html
