CREATE TABLE candidate
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name  VARCHAR(255)                            NOT NULL,
    last_name   VARCHAR(255)                            NOT NULL,
    patronymic  VARCHAR(255)                            NOT NULL,
    description VARCHAR(255)                            NOT NULL,
    photo_id    VARCHAR(255)                            NOT NULL,
    cv_id       VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_candidate PRIMARY KEY (id)
);

CREATE TABLE candidate_speciality
(
    candidate_id  BIGINT NOT NULL,
    speciality_id BIGINT NOT NULL,
    CONSTRAINT pk_candidate_speciality PRIMARY KEY (candidate_id, speciality_id)
);

CREATE TABLE file
(
    id           VARCHAR(255) NOT NULL,
    name         VARCHAR(255) NOT NULL,
    content_type VARCHAR(255) NOT NULL,
    size         BIGINT       NOT NULL,
    data         bytea        NOT NULL,
    CONSTRAINT pk_file PRIMARY KEY (id)
);

CREATE TABLE speciality
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    description VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_speciality PRIMARY KEY (id)
);

CREATE TABLE test
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name          VARCHAR(255)                            NOT NULL,
    description   VARCHAR(255)                            NOT NULL,
    speciality_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_test PRIMARY KEY (id)
);

CREATE TABLE candidate_test
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    test_id      BIGINT                                  NOT NULL,
    candidate_id BIGINT                                  NOT NULL,
    grade        INTEGER                                 NOT NULL,
    passed_at    DATE                                    NOT NULL,
    CONSTRAINT pk_candidate_test PRIMARY KEY (id)
);

ALTER TABLE candidate
    ADD CONSTRAINT uc_candidate_cv UNIQUE (cv_id);

ALTER TABLE candidate
    ADD CONSTRAINT uc_candidate_photo UNIQUE (photo_id);

ALTER TABLE speciality
    ADD CONSTRAINT uc_speciality_name UNIQUE (name);

ALTER TABLE test
    ADD CONSTRAINT uc_test_name UNIQUE (name);

ALTER TABLE candidate
    ADD CONSTRAINT FK_CANDIDATE_ON_CV FOREIGN KEY (cv_id) REFERENCES file (id);

ALTER TABLE candidate
    ADD CONSTRAINT FK_CANDIDATE_ON_PHOTO FOREIGN KEY (photo_id) REFERENCES file (id);

ALTER TABLE test
    ADD CONSTRAINT FK_TEST_ON_SPECIALITY FOREIGN KEY (speciality_id) REFERENCES speciality (id);

ALTER TABLE candidate_test
    ADD CONSTRAINT FK_CANDIDATE_TEST_ON_CANDIDATE FOREIGN KEY (candidate_id) REFERENCES candidate (id);

ALTER TABLE candidate_test
    ADD CONSTRAINT FK_CANDIDATE_TEST_ON_TEST FOREIGN KEY (test_id) REFERENCES test (id);

ALTER TABLE candidate_speciality
    ADD CONSTRAINT fk_canspe_on_candidate FOREIGN KEY (candidate_id) REFERENCES candidate (id);

ALTER TABLE candidate_speciality
    ADD CONSTRAINT fk_canspe_on_speciality FOREIGN KEY (speciality_id) REFERENCES speciality (id);
